### ISSUE TITLE
Can't find <smooth/core/io/Output.h>

### ISSUE THREAD

**Issue by nosovandrew** [COM8/esp32-xmpp-iot#1]
I cloned repo into esp-idf examples, then install submodules and run "make flash" inside of ESP32 folder. Now I got error:

```
In file included from /Users/andrewnosov/Development/diploma/esp-idf/examples/esp32-xmpp-iot/ESP32/main/esp/WifiTask.hpp:3,
                 from /Users/andrewnosov/Development/diploma/esp-idf/examples/esp32-xmpp-iot/ESP32/main/EspIoT.hpp:4,
                 from /Users/andrewnosov/Development/diploma/esp-idf/examples/esp32-xmpp-iot/ESP32/main/EspIoT.cpp:1:
/Users/andrewnosov/Development/diploma/esp-idf/examples/esp32-xmpp-iot/ESP32/main/esp/actuators/RgbLed.hpp:4:10: fatal error: smooth/core/io/Output.h: No such file or directory
 #include <smooth/core/io/Output.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [EspIoT.o] Error 1
make: *** [component-main-build] Error 2
```

How I can solve it?
Thanks in advance!

**Comment by COM8** [comment]
This is probably caused by me using `.gitmodules` and always using the latest master from [smooth](https://github.com/PerMalmberg/Smooth).
Try using an older commit. Everything before https://github.com/PerMalmberg/Smooth/commit/24a828e128b93db1c06f3086b37d1af2fcdbdbec should work.

https://github.com/COM8/esp32-xmpp-iot/blob/32836ff25730f8ae57180e2f5748a8100963ea8d/.gitmodules#L1-L3

**Comment by nosovandrew** [comment]
@COM8 
I've moved to [f8b54da](https://github.com/PerMalmberg/Smooth/commit/f8b54da045c2d43b1366bcc60749ba28b1ffd6c6), but it can't help, I have the same error.

May be I'm doing something wrong? My steps:

- instal esp-idf;
- clone your project to examples folder;
- run `git submodule update --init --recursive`;
- checkout to old Smooth commit;
- move to ESP32 folder and run `make flash`.

That's all.

**Comment by COM8** [comment]
Try:
```bash
cd ESP32 && bash init.sh
```

**Comment by COM8** [comment]
Also I'm using `release/v4.3` of the esp-idf.

**Comment by nosovandrew** [comment]
@COM8 What about `/tmp/esp32-snippets`? I added empty folders and run init.sh, then got:
```
andrewnosov@MacBook-Andrew ESP32 % bash init.sh
Cloning into '/tmp/esp32-snippets'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
cp: /tmp/esp32-snippets/cpp_utils/: No such file or directory
```

**Comment by COM8** [comment]
Ah, please pull and try again.
I changed the git url from ssh to https

**Comment by nosovandrew** [comment]
@COM8 It solved my problem, thanks!🎉

Now, when I ran `idf.py build` I got an error:
```
CMake Error at /Users/andrewnosov/Development/diploma/esp-idf/tools/cmake/build.cmake:194 (message):
  Failed to resolve component 'cpp_utils'.
Call Stack (most recent call first):
  /Users/andrewnosov/Development/diploma/esp-idf/tools/cmake/build.cmake:220 (__build_resolve_and_add_req)
  /Users/andrewnosov/Development/diploma/esp-idf/tools/cmake/build.cmake:508 (__build_expand_requirements)
  /Users/andrewnosov/Development/diploma/esp-idf/tools/cmake/project.cmake:361 (idf_build_process)
  CMakeLists.txt:20 (project)


-- Configuring incomplete, errors occurred!
```

I have latest version of esp-idf. If you have some thoughts about this, tell me please. If not, then I'll figure it out on my own.

**Comment by COM8** [comment]
Looks to me like `bash init.sh` was not successful.
Please try:
```
cd ESP32
idf.py fullclean
bash init.sh
idf.py build
```

**Comment by nosovandrew** [comment]
@COM8 I've tried, but without any success(

**Comment by COM8** [comment]
What is the contents of your `ESP32/components/cpp_utils/` directory?
In case it's empty, try performing the steps inside the `init.sh` manually.

**Comment by nosovandrew** [comment]
@COM8 There is no `cpp_utils` in components folder, and after manual running all init commands nothing changed.

Also after command `git clone https://github.com/COM8/esp32-snippets.git /tmp/esp32-snippets` there is no `/tmp/esp32-snippets` and after `cp -r /tmp/esp32-snippets/cpp_utils/ components/` cpp_utils is absent.

Could you send me completed directory (builded and ready for flashing)? For example in Google Cloud, Dropbox or something like that.
